language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
    pip install -r requirements.txt
script:
    python test_uritemplate.py
notifications:
   on_success: change
   on_failure: change
